print( " 10 can be divided by 5,so its a buzz")
print( " 20 can be divided by 5 so its a buzz")
print( " 30 can be divided by 5 and 3 so its a fizzbuzz")
print( " 40 can be divided by 5 so its  buzz")
print( " 50 can be divided by 5 so its buzz")
print( " 60 can be divided by 5 so its buzz ")
print( " 70 can be divided by 5 so its buzz ")
print( " 80 can be divided by 5 so its buzz ")
print( " 90 can be divided by 5 and 3 so its fizzbuzz")
print( " 100 cam be divided by 5 so its a buzz") 